### ISSUE TITLE
layout/general 

### ISSUE THREAD

**Issue by lewbager** [jamieshepherd/tygr#23] opened 2015-02-02 16:27 UTC
At 1024x768 the projects resize slightly oddly and there are some overlaps with buttons over content. Not a big deal, but just fyi:
 http://puu.sh/fnoyf/4a2b9c8b37.png

**Comment by jamieshepherd** [comment] 2015-02-02 16:29
Duplicate of #2

**Closed as completed by jamieshepherd** 2015-02-02 16:29 UTC
Labels: duplicate
