### ISSUE TITLE
'Log an issue' page

### ISSUE THREAD

**Issue by StephenHodge** [jamieshepherd/tygr#27] opened 2015-02-03 12:45 UTC
Would be good that the client has to give the URL for the resource they're working on prehaps have this as a required field this way we don't have issues of 'well it looks fixed on my screen' only for them to be using vesion 0.14 of the spanish translation when we're looking at French v5....

Be particularly useful for things like JIBS where we have multiple versions of essentially the same project

**Comment by StephenHodge** [comment] 2015-02-03 12:48
I see you've got 'current version' and such thingson the module page, so I guess your already thinking along those lines. I guess if the user just pastes in the URL we could fetch (that the term) the version number from that URL?

**Comment by jamieshepherd** [comment] 2015-02-03 12:58
Clients will actually only be able to write issues for the current version of the project, I plan on being able to move issues if they don't get resolved on v1 to v2 for example, but they should only be able actually create an issue for the current version. Perhaps we should show them the project version that the issue is assigned to on the actual issue (it shows in the index currently)

**Closed as completed** 2015-02-03 13:44 UTC
Labels: enhancement
